dist: trusty
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

install: yarn bootstrap

jobs:
  include:
    - script: yarn lint
    - script: yarn test