dist: trusty
language: node_js
node_js:
  - '8'
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - .npm
    - node_modules

install: yarn

branches:
  only:
    - master

script:
  - yarn lint
  - yarn test:ci && yarn coverage:upload
  - yarn build

# stages:
#   - lint
#   - test
#   - build

# jobs:
#   include:
#     - stage: lint
