dist: trusty
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add lerna@3.4.3

cache:
  yarn: true
  directories:
    - .npm

install: yarn bootstrap

script:
  - yarn lint
  - yarn test
  - yarn build

# stages:
#   - lint
#   - test
#   - build

# jobs:
#   include:
#     - stage: lint
