version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - "~/.cache/yarn"
      - run:
          name: test
          command: yarn test
