import ANDROID_VERSION_I from './android-version';
import DEVICE_TYPE_I from './device-type';
import FIREFOX_VERSION_I from './firefox-version';
import HAS_CANVAS_I from './has-canvas';
import HAS_FULLSCREEN_I from './has-fullscreen';
import HAS_GYRO_I from './has-gyro';
import HAS_HISTORY_I from './has-history';
import HAS_INLINE_VIDEO_FORCED_I from './has-inline-video-forced';
import HAS_INLINE_VIDEO_I from './has-inline-video';
import HAS_MOUSE_MOVE_I from './has-mouse-move';
import HAS_TOUCH_I from './has-touch';
import HAS_WEBGL_I from './has-webgl';
import HIDDEN_PROPERTY_NAME_I from './hidden-property-name';
import IE_VERSION_I from './ie-version';
import IOS_VERSION_I from './ios-version';
import IS_ANDROID_BROWSER_I from './is-android-browser';
import IS_ANDROID_I from './is-android';
import IS_CHROME_IOS_I from './is-chrome-ios';
import IS_CHROME_I from './is-chrome';
import IS_DESKTOP_I from './is-desktop';
import IS_FIREFOX_I from './is-firefox';
import IS_IE_I from './is-ie';
import IS_IOS_I from './is-ios';
import IS_IPAD_I from './is-ipad';
import IS_IPHONE_I from './is-iphone';
import IS_IPOD_I from './is-ipod';
import IS_LINUX_I from './is-linux';
import IS_MOBILE_I from './is-mobile';
import IS_OPERA_I from './is-opera';
import IS_OSX_I from './is-osx';
import IS_PHONE_I from './is-phone';
import IS_RETINA_I from './is-retina';
import IS_SAFARI_IOS_I from './is-safari-ios';
import IS_SAFARI_I from './is-safari';
import IS_TABLET_I from './is-tablet';
import IS_WINDOWS_PHONE_I from './is-windows-phone';
import IS_WINDOWS_I from './is-windows';
import MAX_CUBE_TEXTURE_SIZE_I from './max-cube-texture-size';
import PIXEL_RATIO_I from './pixel-ratio';
import TRANSITION_END_EVENT_NAME_I from './transition-end-event-name';
import UA_I from './ua';
import VISIBILITY_CHANGE_EVENT_NAME_I from './visibility-change-event-name';


export const ANDROID_VERSION = ANDROID_VERSION_I;
export const DEVICE_TYPE = DEVICE_TYPE_I;
export const FIREFOX_VERSION = FIREFOX_VERSION_I;
export const HAS_CANVAS = HAS_CANVAS_I;
export const HAS_FULLSCREEN = HAS_FULLSCREEN_I;
export const HAS_GYRO = HAS_GYRO_I;
export const HAS_HISTORY = HAS_HISTORY_I;
export const HAS_INLINE_VIDEO_FORCED = HAS_INLINE_VIDEO_FORCED_I;
export const HAS_INLINE_VIDEO = HAS_INLINE_VIDEO_I;
export const HAS_MOUSE_MOVE = HAS_MOUSE_MOVE_I;
export const HAS_TOUCH = HAS_TOUCH_I;
export const HAS_WEBGL = HAS_WEBGL_I;
export const HIDDEN_PROPERTY_NAME = HIDDEN_PROPERTY_NAME_I;
export const IE_VERSION = IE_VERSION_I;
export const IOS_VERSION = IOS_VERSION_I;
export const IS_ANDROID = IS_ANDROID_I;
export const IS_ANDROID_BROWSER = IS_ANDROID_BROWSER_I;
export const IS_CHROME_IOS = IS_CHROME_IOS_I;
export const IS_CHROME = IS_CHROME_I;
export const IS_DESKTOP = IS_DESKTOP_I;
export const IS_FIREFOX = IS_FIREFOX_I;
export const IS_IE = IS_IE_I;
export const IS_IOS = IS_IOS_I;
export const IS_IPAD = IS_IPAD_I;
export const IS_IPHONE = IS_IPHONE_I;
export const IS_IPOD = IS_IPOD_I;
export const IS_LINUX = IS_LINUX_I;
export const IS_MOBILE = IS_MOBILE_I;
export const IS_OPERA = IS_OPERA_I;
export const IS_OSX = IS_OSX_I;
export const IS_PHONE = IS_PHONE_I;
export const IS_RETINA = IS_RETINA_I;
export const IS_SAFARI_IOS = IS_SAFARI_IOS_I;
export const IS_SAFARI = IS_SAFARI_I;
export const IS_TABLET = IS_TABLET_I;
export const IS_WINDOWS_PHONE = IS_WINDOWS_PHONE_I;
export const IS_WINDOWS = IS_WINDOWS_I;
export const MAX_CUBE_TEXTURE_SIZE = MAX_CUBE_TEXTURE_SIZE_I;
export const PIXEL_RATIO = PIXEL_RATIO_I;
export const TRANSITION_END_EVENT_NAME = TRANSITION_END_EVENT_NAME_I;
export const UA = UA_I;
export const VISIBILITY_CHANGE_EVENT_NAME = VISIBILITY_CHANGE_EVENT_NAME_I;
